### ISSUE TITLE
Move to master-only branching model

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/katuma-landing-page#14]
## What

Given the small attention we paid to our landing page plus the lack of concurrency of devs working on it and its simplicity, having both a `develop` and `master` branches brings an unnecessary overhead. 

Because we deploy small fixes and improvements as soon as we have them ready, the `master` branch is becoming stale due to the fact that we deploy `develop` as soon as a PR is merged. So as it is now, the `master` serves no purpose.

I propose merging `develop` into `master` and removing `develop`. Then, all feature branches will be merged into `master` instead.

**Comment by sauloperez** [comment]
Now that we have github pages enabled, solving this issue will allow us to remove `gh-pages` branch as well and point them to `master` instead.

**Comment by enricostano** [comment]
Yep, but remember that we deploy merging into `gh-pages` branch

**Comment by enricostano** [comment]
Ok

**Comment by sauloperez** [comment]
That's exactly what I suggest changing

**Comment by sauloperez** [comment]
I just made `master` the new default branch and removed `develop`
