### ISSUE TITLE
Split locales into per-section files

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/katuma-landing-page#35]
So far it's been quite hard to add new translation copies as the language files get larger. It is hard to know where in the JSON you are adding the copy and this leads to errors.

I gave a quick look at [i18next's namespaces](https://www.i18next.com/principles/namespaces) (the lib we use for i18n) but I didn't manage to make it work.

Ideally, the goal is to have a folder for each language such as `locales/ca/` and then a `footer.json`, `features.json`, `sponsors.json` and `index.json`. That might not be the only solution though.

**Comment by sauloperez** [comment]
Now that #36 got merged, we need to follow the approach and do the same to extract `features.json`, `sponsors.json` and `index.json`.

**Comment by Inkala** [comment]
I would like to work on this.

**Comment by sauloperez** [comment]
Go ahead @Inkala . All yours.

**Comment by sauloperez** [comment]
Closed by #41
