### ISSUE TITLE
Repo outdated?

### ISSUE THREAD

**Issue by mllocs** [coopdevs/katuma-landing-page#6]
Hello! 👋 
I wanted to submit a PR to fix a typo and to add translations for another language but I noticed that the content of this repo is not the same as the one in katuma.org ¯\_(ツ)_/¯
How can I contribute? 😄 
Thanks!

**Comment by enricostano** [comment]
https://github.com/coopdevs/katuma-landing-page/pull/5 ask @sseerrggii
