### ISSUE TITLE
Footer link GH points to https://github.com/coopdevs

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/katuma-landing-page#61]
Should be https://github.com/openfoodfoundation/openfoodnetwork

**Comment by lumie31** [comment]
Hello, @sseerrggii Is this issue still open and relevant? I see the suggested link above points to a GitHub URL. Should it point to the openfoodnetwork website either?

**Comment by sauloperez** [comment]
Hi @lumie31 and welcome! yes, it's still relevant. As @sseerrggii suggests it should point to that Github's repo instead.

**Comment by lumie31** [comment]
Hi @sauloperez. Thanks for your response above. I've been trying to get the project running on my local machine for a while now and I keep getting a dependencies error of some sort

- I use a windows 10 pc
- I have never done anything with ruby before and on this machine, so just familiarizing myself with the ruby lingo

For clarity, this is the error I keep getting when I try to install project dependencies:
```
Bundler could not find compatible versions for gem "ruby ":
  In Gemfile:
    ruby

    ffi (>= 1.9.24) was resolved to 1.9.25, which depends on
      ruby  (< 2.6) x64-mingw32

Could not find gem 'ruby  (< 2.6)', which is required by gem 'ffi (>= 1.9.24)',
in any of the relevant sources:
  the local ruby installation
```

Will keep trying to get it to work over here, just thought i should keep you in the know

**Comment by sauloperez** [comment]
Hi @lumie31 !

I'm very sorry but I might not the best person to help you set up a win machine. I haven't touched one in ages.

Unfortunately, by the error message you shared looks like your windows machine is not compatible with the Ruby version we use and the `ffi` gem. Jekyll itself claims not to be compatible with Windows

> While Windows is not an officially-supported platform, it can be used to run Jekyll with the proper tweaks. This page aims to collect some of the general knowledge and lessons that have been unearthed by Windows users.

https://jekyllrb.com/docs/installation/windows/

I think the best you can do for this and other dev projects (as they say in the doc above) is to install [Linux on Windows](https://docs.microsoft.com/ca-es/windows/wsl/about?redirectedfrom=MSDN).

**Comment by lumie31** [comment]
@sauloperez Oh thanks for the response and the suggestions above. I've actually tried several things to get the project running over here but all to no avail. 

I could fix the link without testing it though like you suggested, but it just seems weird fixing something without testing but if that works, then no problems

**Comment by sauloperez** [comment]
Fortunately,  I just merged Docker support today and that should allow you to run the site in a container. You'll find the instructions in https://github.com/coopdevs/katuma-landing-page/blob/master/README.md#development
