### ISSUE TITLE
Flow Chart

### ISSUE THREAD

**Issue by abdikarso** [coopdevs/katuma-landing-page#63]
Maybe you need to adding a Flow Chart for your setup

**Comment by sauloperez** [comment]
Hi @abdikarso ! so far the setup is very simple as it's only a Jekyll site with a couple of pages and we want to keep that simplicity to keep costs low. We prefer to focus on other issues. I hope you understand.

Don't hesitate to suggest any further improvements taking that into account. All feedback is welcome!
